name: Event workflow
on:
  workflow_dispatch:
    inputs: 
      input-example: 
        type: string
        description: "Input test"
        required: true
jobs:
  teste:
    runs-on: ubuntu_latest
    steps:
      - name: Test Action
        run: echo "Input event has been triggered:, ${{ inputs.input-example }}"
