name: Push event 
on:
  push:
    # tags: 
      # - v*
    # branches-ignore: 
    branches: ["main", "features/*"]
    paths: 
      - "src/**"
jobs:  
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "Push action"
        run: echo "Push action on features"
  
