name: Push event 
on:
  push:
    tags: 
      - v*
    # branches: ["main", "feature/*"]
jobs:  
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "Push action"
        run: echo "Push action on features"
  
