name: Push event 
on:
  pull_request:
  # push:
    # tags: 
      # - v*
    # branches-ignore: 
    branches: ["main"]
    # paths: 
    #   - "src/**"
jobs:  
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "Push action"
        run: echo "Push action on features"
  
