name: Push event 
on:
  pull_request:
  # push:
    # tags: 
      # - v*
    # branches-ignore: 
    branches: ["main"]
    # paths: 
    #   - "src/**"
jobs:  
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "Push action"
        run: echo "Push action on features"
      - name: "Changing card"
        uses: actions/github-script@v6
        with: 
          script: | 
            github.rest.issue.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.owner,
              body: 'Adding comment about the PR'
            })
  
